#!/usr/bin/env sh
set -eu

HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
CHECK="${HERE}/third-party-licenses.sh"
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "${TEMP_DIR}"' EXIT

LOCK="${TEMP_DIR}/Cargo.lock"
INVENTORY="${TEMP_DIR}/inventory.md"

cat > "${LOCK}" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "alpha"
version = "1.2.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "beta"
version = "0.4.0"

[[package]]
name = "keepafloatd"
version = "0.1.0"
dependencies = [
 "alpha",
 "beta",
]
LOCK

write_inventory() {
  cat > "${INVENTORY}" <<INVENTORY
# Third-Party License Inventory

- Scope: \`cargo metadata --format-version 1 --locked\`
- Non-root crates observed: \`$1\`
- Distinct third-party license expressions observed: \`$2\`

## Observed License Expressions

- \`MIT\`
- \`MIT OR Apache-2.0\`

## Packages by Expression

### \`MIT\`

- \`alpha\` \`$3\`

### \`MIT OR Apache-2.0\`

- \`beta\` \`0.4.0\`
INVENTORY
}

write_inventory 2 2 1.2.3
"${CHECK}" "${LOCK}" "${INVENTORY}" >/dev/null

write_inventory 2 2 1.2.2
if output="$("${CHECK}" "${LOCK}" "${INVENTORY}" 2>&1)"; then
  echo "license inventory check accepted a stale crate version" >&2
  exit 1
fi
case "${output}" in
  *"alpha 1.2.2"*"alpha 1.2.3"*) ;;
  *) echo "license inventory check did not name the stale and current versions: ${output}" >&2; exit 1 ;;
esac

write_inventory 3 2 1.2.3
if output="$("${CHECK}" "${LOCK}" "${INVENTORY}" 2>&1)"; then
  echo "license inventory check accepted a wrong crate count" >&2
  exit 1
fi
case "${output}" in
  *"crate count 3"*"lockfile has 2"*) ;;
  *) echo "license inventory check did not report the crate count mismatch: ${output}" >&2; exit 1 ;;
esac

write_inventory 2 1 1.2.3
if output="$("${CHECK}" "${LOCK}" "${INVENTORY}" 2>&1)"; then
  echo "license inventory check accepted a wrong expression count" >&2
  exit 1
fi
case "${output}" in
  *"expression count 1"*"inventory lists 2"*) ;;
  *) echo "license inventory check did not report the expression count mismatch: ${output}" >&2; exit 1 ;;
esac

echo "Third-party license inventory regression checks passed"
